import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#fafaf5",
  },
  content: {
    padding: 24,
    paddingBottom: 32,
    gap: 24,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  topBarLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  iconText: {
    color: "#0d631b",
    fontSize: 16,
    fontWeight: "900",
  },
  topTitle: {
    color: "#0d631b",
    fontSize: 18,
    fontWeight: "800",
  },
  brand: {
    color: "#0d631b",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.8,
  },
  heroSection: {
    gap: 12,
  },
  stepBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#feb300",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  stepBadgeText: {
    color: "#6a4800",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: "#1a1c19",
    fontSize: 40,
    lineHeight: 42,
    fontWeight: "900",
    letterSpacing: -1.2,
  },
  heroAccent: {
    color: "#0d631b",
  },
  heroCopy: {
    color: "#40493d",
    fontSize: 16,
    lineHeight: 26,
    maxWidth: 520,
  },
  memberCard: {
    backgroundColor: "#f4f4ef",
    borderRadius: 18,
    padding: 24,
    gap: 20,
  },
  memberHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  memberLabel: {
    color: "#0d631b",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  memberTitle: {
    color: "#1a1c19",
    fontSize: 22,
    fontWeight: "800",
    marginTop: 4,
  },
  memberStatus: {
    color: "#2e7d32",
    fontSize: 16,
    fontWeight: "900",
  },
  memberGrid: {
    gap: 16,
  },
  fieldWrap: {
    gap: 8,
  },
  fieldLabel: {
    color: "#40493d",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    paddingHorizontal: 2,
  },
  staticField: {
    minHeight: 54,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(191,202,186,0.28)",
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  staticFieldText: {
    color: "#1a1c19",
    fontSize: 18,
    fontWeight: "600",
  },
  newMemberCard: {
    backgroundColor: "#e2e3de",
    borderRadius: 18,
    padding: 24,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "rgba(191,202,186,0.45)",
    gap: 22,
  },
  newMemberHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  memberNumber: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#0d631b",
    alignItems: "center",
    justifyContent: "center",
  },
  memberNumberText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  newMemberTitle: {
    color: "#1a1c19",
    fontSize: 22,
    fontWeight: "800",
  },
  formGrid: {
    gap: 18,
  },
  inputField: {
    minHeight: 56,
    backgroundColor: "#f4f4ef",
    borderBottomWidth: 2,
    borderBottomColor: "rgba(191,202,186,0.28)",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingHorizontal: 16,
    color: "#1a1c19",
    fontSize: 16,
  },
  selectField: {
    minHeight: 56,
    backgroundColor: "#f4f4ef",
    borderBottomWidth: 2,
    borderBottomColor: "rgba(191,202,186,0.28)",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  selectText: {
    color: "#1a1c19",
    fontSize: 16,
  },
  placeholderText: {
    color: "#7d867b",
  },
  relationshipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  relationshipChip: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "rgba(191,202,186,0.35)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  relationshipChipText: {
    color: "#40493d",
    fontSize: 12,
    fontWeight: "600",
  },
  inputWithIcon: {
    minHeight: 56,
    backgroundColor: "#f4f4ef",
    borderBottomWidth: 2,
    borderBottomColor: "rgba(191,202,186,0.28)",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconInputField: {
    flex: 1,
    color: "#1a1c19",
    fontSize: 16,
  },
  inputIcon: {
    color: "rgba(64,73,61,0.5)",
    fontSize: 18,
    fontWeight: "800",
  },
  quickSelectSection: {
    gap: 12,
    paddingTop: 6,
  },
  quickSelectRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  needChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(191,202,186,0.4)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#fafaf5",
  },
  needChipActive: {
    backgroundColor: "#0d631b",
    borderColor: "#0d631b",
  },
  needChipIcon: {
    color: "#1a1c19",
    fontSize: 14,
    fontWeight: "900",
  },
  needChipIconActive: {
    color: "#ffffff",
  },
  needChipText: {
    color: "#1a1c19",
    fontSize: 13,
    fontWeight: "600",
  },
  needChipTextActive: {
    color: "#ffffff",
  },
  actionRow: {
    gap: 12,
    paddingTop: 4,
  },
  secondaryButton: {
    minHeight: 56,
    borderRadius: 16,
    backgroundColor: "#e2e3de",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
  },
  secondaryButtonIcon: {
    color: "#1a1c19",
    fontSize: 18,
    fontWeight: "900",
  },
  secondaryButtonText: {
    color: "#1a1c19",
    fontSize: 16,
    fontWeight: "800",
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 16,
    backgroundColor: "#0d631b",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
    shadowColor: "#0d631b",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  primaryButtonArrow: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  sidebarCard: {
    backgroundColor: "rgba(46,125,50,0.1)",
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(46,125,50,0.12)",
    gap: 10,
  },
  sidebarIcon: {
    color: "#0d631b",
    fontSize: 18,
    fontWeight: "900",
  },
  sidebarTitle: {
    color: "#0d631b",
    fontSize: 18,
    fontWeight: "800",
  },
  sidebarCopy: {
    color: "#40493d",
    fontSize: 13,
    lineHeight: 21,
  },
  imageCard: {
    height: 256,
    borderRadius: 18,
    overflow: "hidden",
    position: "relative",
  },
  imageCardPhoto: {
    width: "100%",
    height: "100%",
  },
  imageCardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(13,99,27,0.42)",
    justifyContent: "flex-end",
    padding: 20,
  },
  imageCardQuote: {
    color: "#ffffff",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  privacyCard: {
    backgroundColor: "#e8e8e4",
    borderRadius: 18,
    padding: 20,
    gap: 10,
  },
  privacyHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  privacyIcon: {
    color: "#7e5700",
    fontSize: 16,
    fontWeight: "900",
  },
  privacyTitle: {
    color: "#40493d",
    fontSize: 18,
    fontWeight: "800",
  },
  privacyCopy: {
    color: "rgba(64,73,61,0.78)",
    fontSize: 12,
    lineHeight: 20,
  },
});
