import { StyleSheet } from "react-native";
import { theme, fonts } from "../theme";

export const styles = StyleSheet.create({
  hero: {
    gap: 12,
  },
  heroTitle: {
    color: "#fff",
    fontSize: 32,
    lineHeight: 34,
    ...fonts.black,
  },
  heroText: {
    color: "rgba(255,255,255,0.88)",
    lineHeight: 22,
  },
  actions: {
    gap: 10,
    marginTop: 16,
  },
  citizenShell: {
    gap: 18,
    flex: 1,
  },
  orb: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.1,
  },
  orb1: {
    width: 250,
    height: 250,
    backgroundColor: theme.primary,
    top: -100,
    right: -100,
  },
  orb2: {
    width: 200,
    height: 200,
    backgroundColor: "#FFB300",
    bottom: "20%",
    left: -80,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255,255,255,0.8)",
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    zIndex: 10,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0f2ee",
  },
  menuButtonText: {
    color: theme.primary,
    fontSize: 22,
    ...fonts.bold,
  },
  brandText: {
    color: theme.primary,
    fontSize: 22,
    ...fonts.black,
    letterSpacing: -0.8,
  },
  roleBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  roleTag: {
    color: theme.textMuted,
    fontSize: 10,
    ...fonts.extrabold,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    textAlign: "right",
  },
  avatarIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f0f2ee",
    alignItems: "center",
    justifyContent: "center",
  },
  editorialPanel: {
    gap: 14,
    paddingHorizontal: 4,
  },
  gatewayLabel: {
    textTransform: "uppercase",
    letterSpacing: 2.4,
    ...fonts.extrabold,
    fontSize: 11,
  },
  editorialTitle: {
    color: "#1a1c19",
    fontSize: 38,
    lineHeight: 40,
    ...fonts.black,
    letterSpacing: -1.4,
  },
  editorialAccent: {
    fontStyle: "italic",
    opacity: 0.8,
  },
  editorialText: {
    color: "#40493d",
    fontSize: 15,
    lineHeight: 24,
  },
  imageCard: {
    height: 180,
    borderRadius: 28,
    overflow: "hidden",
    justifyContent: "flex-end",
    backgroundColor: "#e8ede7",
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.02)",
  },
  imageFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 18,
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  verifiedIcon: {
    fontSize: 18,
    ...fonts.black,
  },
  imageFooterText: {
    fontSize: 11,
    ...fonts.extrabold,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  loginCard: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: "#ffffff",
    borderRadius: 32,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
    marginBottom: 20,
  },
  glowOrb: {
    position: "absolute",
    top: -40,
    right: -40,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(0,0,0,0.03)",
  },
  loginCardInner: {
    gap: 24,
    padding: 24,
  },
  loginIntro: {
    gap: 6,
  },
  loginTitle: {
    color: "#1a1c19",
    fontSize: 30,
    ...fonts.black,
  },
  loginSubtitle: {
    color: "#40493d",
    fontSize: 14,
    lineHeight: 21,
  },
  fieldGroup: {
    gap: 10,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  fieldLabel: {
    color: theme.textMuted,
    fontSize: 11,
    ...fonts.extrabold,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  helpLink: {
    fontSize: 10,
    ...fonts.extrabold,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  fieldWrap: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 16,
    backgroundColor: "#f5f6f4",
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.03)",
  },
  fieldIcon: {
    color: theme.textLight,
    fontSize: 18,
  },
  fieldInput: {
    flex: 1,
    color: "#1a1c19",
    fontSize: 16,
    ...fonts.medium,
  },
  visibilityToggle: {
    color: theme.textLight,
    fontSize: 12,
    ...fonts.bold,
  },
  actionStack: {
    gap: 16,
    marginTop: 8,
  },
  primaryAction: {
    borderRadius: 20,
    overflow: "hidden",
    height: 60,
  },
  primaryGradient: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  primaryActionText: {
    color: "#ffffff",
    fontSize: 15,
    ...fonts.black,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  primaryActionArrow: {
    color: "#ffffff",
    fontSize: 20,
    ...fonts.black,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(0,0,0,0.06)",
  },
  dividerText: {
    color: theme.textLight,
    fontSize: 11,
    ...fonts.extrabold,
    letterSpacing: 1.2,
  },
  secondaryAction: {
    height: 56,
    borderRadius: 20,
    backgroundColor: "#f0f2ee",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.03)",
  },
  secondaryActionText: {
    color: theme.text,
    fontSize: 14,
    ...fonts.bold,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  footer: {
    gap: 16,
    paddingHorizontal: 4,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    paddingTop: 24,
  },
  footerLinks: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
  },
  footerLink: {
    color: theme.textMuted,
    fontSize: 12,
    ...fonts.bold,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  footerNote: {
    color: theme.textLight,
    fontSize: 11,
    lineHeight: 16,
  },
});
