import { StyleSheet } from "react-native";
import { theme, fonts } from "../theme";

export const styles = StyleSheet.create({
  hero: {
    gap: 12,
  },
  heroTitle: {
    color: "#fff",
    fontSize: 32,
    lineHeight: 34,
    ...fonts.black,
  },
  heroText: {
    color: "rgba(255,255,255,0.88)",
    lineHeight: 22,
  },
  actions: {
    gap: 10,
    marginTop: 16,
  },
  citizenShell: {
    gap: 18,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(250,250,245,0.92)",
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "rgba(112,122,108,0.14)",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#edf1e8",
  },
  menuButtonText: {
    color: "#0d631b",
    fontSize: 22,
    ...fonts.bold,
  },
  brandText: {
    color: "#0d631b",
    fontSize: 22,
    ...fonts.black,
    letterSpacing: -0.8,
  },
  roleBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  roleTag: {
    color: "#0d631b",
    fontSize: 10,
    ...fonts.extrabold,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    maxWidth: 86,
    textAlign: "right",
  },
  avatarImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#e8e8e4",
  },
  editorialPanel: {
    gap: 14,
  },
  gatewayLabel: {
    color: "#7e5700",
    textTransform: "uppercase",
    letterSpacing: 2.4,
    ...fonts.extrabold,
    fontSize: 11,
  },
  editorialTitle: {
    color: "#1a1c19",
    fontSize: 38,
    lineHeight: 40,
    ...fonts.black,
    letterSpacing: -1.4,
  },
  editorialAccent: {
    color: "#0d631b",
    fontStyle: "italic",
  },
  editorialText: {
    color: "#40493d",
    fontSize: 15,
    lineHeight: 24,
  },
  imageCard: {
    height: 220,
    borderRadius: 28,
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  editorialImage: {
    borderRadius: 28,
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.18)",
  },
  imageFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 18,
  },
  verifiedIcon: {
    color: "#ffdeac",
    fontSize: 18,
    ...fonts.black,
  },
  imageFooterText: {
    color: "#ffffff",
    fontSize: 11,
    ...fonts.extrabold,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  loginCard: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: "#ffffff",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(112,122,108,0.12)",
    shadowColor: "#1a1c19",
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  glowOrb: {
    position: "absolute",
    top: -36,
    right: -18,
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: "rgba(13,99,27,0.08)",
  },
  loginCardInner: {
    gap: 22,
    padding: 24,
  },
  loginIntro: {
    gap: 6,
  },
  loginTitle: {
    color: "#1a1c19",
    fontSize: 28,
    ...fonts.black,
  },
  loginSubtitle: {
    color: "#40493d",
    fontSize: 14,
    lineHeight: 21,
  },
  fieldGroup: {
    gap: 10,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  fieldLabel: {
    color: "#40493d",
    fontSize: 11,
    ...fonts.extrabold,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  helpLink: {
    color: "#0d631b",
    fontSize: 10,
    ...fonts.extrabold,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  fieldWrap: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(112,122,108,0.18)",
    backgroundColor: "#f4f4ef",
    paddingHorizontal: 4,
  },
  fieldIcon: {
    width: 28,
    color: "#707a6c",
    textAlign: "center",
    fontSize: 15,
    ...fonts.bold,
  },
  fieldInput: {
    flex: 1,
    minHeight: 54,
    color: "#1a1c19",
    fontSize: 15,
    paddingVertical: 12,
  },
  visibilityToggle: {
    color: "#707a6c",
    fontSize: 12,
    ...fonts.bold,
  },
  actionStack: {
    gap: 14,
    paddingTop: 4,
  },
  primaryAction: {
    borderRadius: 22,
    overflow: "hidden",
  },
  primaryGradient: {
    minHeight: 58,
    borderRadius: 22,
    backgroundColor: theme.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingHorizontal: 20,
  },
  primaryActionText: {
    color: "#ffffff",
    fontSize: 14,
    ...fonts.black,
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  primaryActionArrow: {
    color: "#ffffff",
    fontSize: 18,
    ...fonts.black,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(112,122,108,0.16)",
  },
  dividerText: {
    color: "#707a6c",
    fontSize: 11,
    ...fonts.extrabold,
    letterSpacing: 1.2,
  },
  secondaryAction: {
    minHeight: 56,
    borderRadius: 22,
    backgroundColor: "#e2e3de",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  secondaryActionText: {
    color: "#1a1c19",
    fontSize: 14,
    ...fonts.black,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  altAccessSection: {
    alignItems: "center",
    gap: 14,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: "rgba(112,122,108,0.12)",
  },
  altAccessLabel: {
    color: "rgba(64,73,61,0.7)",
    fontSize: 11,
    ...fonts.extrabold,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  altButtons: {
    flexDirection: "row",
    gap: 14,
  },
  altButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#f4f4ef",
    alignItems: "center",
    justifyContent: "center",
  },
  altButtonIcon: {
    color: "#1a1c19",
    fontSize: 20,
    fontWeight: "700",
  },
  footer: {
    gap: 12,
    paddingHorizontal: 4,
    paddingBottom: 8,
  },
  footerLinks: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  footerLink: {
    color: "#40493d",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  footerNote: {
    color: "rgba(64,73,61,0.58)",
    fontSize: 11,
    lineHeight: 16,
  },
});
