import { StyleSheet } from "react-native";
import { theme, fonts } from "../theme";

export const styles = StyleSheet.create({
  hero: {
    paddingTop: 80,
    paddingBottom: 60,
    backgroundColor: theme.primary,
    borderBottomLeftRadius: 48,
    borderBottomRightRadius: 48,
    marginBottom: 24,
    overflow: "hidden",
    position: "relative",
  },
  heroGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.primaryDeep,
    opacity: 0.5,
  },
  orb: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.15,
  },
  orb1: {
    width: 200,
    height: 200,
    backgroundColor: "#FFB300",
    top: -50,
    right: -50,
  },
  orb2: {
    width: 150,
    height: 150,
    backgroundColor: "#81C784",
    bottom: -30,
    left: -20,
  },
  mark: {
    width: 52,
    height: 52,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  markText: {
    color: "#ffffff",
    fontSize: 24,
    ...fonts.black,
  },
  brand: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 14,
    ...fonts.extrabold,
    letterSpacing: 3,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  headline: {
    color: "#ffffff",
    fontSize: 38,
    lineHeight: 42,
    ...fonts.black,
    marginBottom: 16,
  },
  copy: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 16,
    lineHeight: 24,
    maxWidth: "95%",
    marginBottom: 32,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.15)",
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statValue: {
    color: "#ffffff",
    fontSize: 16,
    ...fonts.bold,
  },
  statLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 11,
    ...fonts.medium,
    textTransform: "uppercase",
    marginTop: 2,
  },
  statDivider: {
    width: 1,
    height: 24,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  selectorHeadText: {
    fontSize: 12,
    color: theme.textLight,
    ...fonts.extrabold,
    letterSpacing: 1.5,
    marginHorizontal: 24,
    marginBottom: 16,
  },
  roleCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.surface,
    padding: 24,
    borderRadius: 32,
    marginBottom: 16,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: theme.line,
    // iOS Shadow
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    // Android Shadow
    elevation: 4,
  },
  roleDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 20,
    marginTop: -40,
  },
  roleCopy: {
    flex: 1,
  },
  roleSub: {
    fontSize: 12,
    ...fonts.extrabold,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 4,
  },
  roleLabel: {
    fontSize: 20,
    color: theme.text,
    ...fonts.black,
    marginBottom: 6,
  },
  roleDesc: {
    fontSize: 14,
    color: theme.textMuted,
    lineHeight: 20,
    maxWidth: "95%",
  },
});
