import { StyleSheet } from "react-native";
import { theme, fonts } from "../theme";

export const siteManagerStyles = StyleSheet.create({
  primaryHero: {
    backgroundColor: theme.primary,
    gap: 12,
  },
  heroTitle: {
    color: "#ffffff",
    fontSize: 30,
    lineHeight: 32,
    ...fonts.black,
  },
  heroText: {
    color: "rgba(255,255,255,0.88)",
    lineHeight: 22,
  },
  sectionTitle: {
    fontSize: 22,
    ...fonts.black,
    color: theme.text,
    marginBottom: 12,
  },
  checkRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    gap: 10,
  },
  checkLabel: {
    flex: 1,
    ...fonts.extrabold,
    color: theme.text,
  },
  scannerBox: {
    height: 180,
    borderRadius: 22,
    backgroundColor: theme.primaryDeep,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  scannerText: {
    color: theme.primaryLight,
    ...fonts.extrabold,
  },
  modeRow: {
    gap: 10,
  },
  manualWrap: {
    marginTop: 14,
    gap: 12,
  },
  helperText: {
    marginTop: 12,
    color: theme.textMuted,
    lineHeight: 20,
  },
  
  // Operational Dashboard Extras
  metricRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  metricCard: {
    flex: 1,
    backgroundColor: theme.surface,
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.line,
    alignItems: "center",
  },
  metricValue: {
    fontSize: 24,
    ...fonts.black,
    color: theme.primary,
  },
  metricLabel: {
    fontSize: 11,
    ...fonts.extrabold,
    color: theme.textMuted,
    textTransform: "uppercase",
    marginTop: 4,
  },
  inventoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
  },
  inventoryItem: {
    width: "48%",
    backgroundColor: theme.surface,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.line,
  },
  inventoryIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: theme.primaryLight,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  progRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  progLabel: {
    fontSize: 13,
    color: theme.text,
    ...fonts.semibold,
  },
  timelineItem: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.primary,
    marginTop: 6,
  },
  timelineLine: {
    position: "absolute",
    left: 4.5,
    top: 16,
    bottom: -20,
    width: 1,
    backgroundColor: theme.line,
  },
  swimlane: {
    paddingBottom: 16,
    paddingTop: 4,
    backgroundColor: theme.surface,
    borderBottomWidth: 1,
    borderColor: theme.line,
  },
  swimScroll: {
    paddingHorizontal: 20,
    gap: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  swimItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  swimLabel: {
    fontSize: 10,
    ...fonts.extrabold,
    color: theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  swimValue: {
    fontSize: 13,
    ...fonts.bold,
    color: theme.text,
  },
  swimDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.success,
  },
  
  // Site Operations Extras
  gaugeContainer: {
    height: 12,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 6,
    overflow: "hidden",
    marginVertical: 12,
  },
  gaugeFill: {
    height: "100%",
    backgroundColor: theme.primary,
  },
  stepperRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: theme.surfaceSoft,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.line,
  },
  stepperBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: theme.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: theme.line,
  },
  stepperValue: {
    fontSize: 20,
    ...fonts.bold,
    color: theme.text,
  },
  distroGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 16,
  },
  distroCard: {
    width: "48%",
    backgroundColor: theme.surface,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.line,
    gap: 12,
  },
  distroIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
});
